jamf/regatta

storage/kv/kv_test.go, storage/kv/map.go, storage/kv/raft.go, storage/kv/raft_test.go, storage/tables/tables.go
Key change highlighted in comment
=> bug: Fix internal KV exists

.github/labeler.yml, docs/_config.yml, docs/contributing.md, docs/proposals/000-rfc-template.md, docs/proposals/proposals.md
Introduces the proposal process. Closes #53.
=> docs: add: proposals

cmd/leader.go, regattaserver/replication.go, storage/table/fsm/fsm.go, storage/table/fsm/fsm_test.go, storage/table/fsm/metrics.go, storage/table/fsm/snapshot_checkpoint.go, storage/table/fsm/snapshot_snapshot.go
Removed the applied index metrics from Replication API, update index in table FSM instead.
Fixes #46
=> bug: do not reach to quorum on replication call

.github/workflows/test.yml
* Push master branch images after merge
* Produce `master` (floating) tag
* Produce `master-<sha>` immutable tag
* None
* In order to test changes before the release
N/A
=> add: output test images from master branch builds

README.md, docs/changelog.md
Update documentation
Fixes #71 
Marks 0.2.0 release
=> docs: update README and release docs

.github/workflows/release.yml
=> bug: fix cosign images

docs/changelog.md
=> docs: v0.2.1 release notes

.github/workflows/release.yml, docs/changelog.md
Fix image signature in release builds.
=> bug: fix cosigning of images

.github/workflows/release.yml, docs/changelog.md, storage/logreader/logreader.go, storage/logreader/logreader_test.go
Fix off by one replication error, when there is a single record to be replicated.
Fixes: #174 
Fixing the bug
* Added a specialized test case to unit tests.
=> bug: fix off by one replication error

docs/proposals/003-replace-raft-lib.md
Design and proposal for Raft implementation replacement.
See the design doc.
=> docs: raft lib replacement proposal

docs/contributing.md, docs/index.md, docs/operations_guide/backups.md, docs/user_guide/delete.md, docs/user_guide/put.md, docs/user_guide/transactions.md, replication/worker.go, storage/cluster/cluster.go, storage/logreader/cache_test.go
Typos in user-visible error messages, documentation, and comments.
Fix misspellings.
=> fix: typos found by codespell

docs/ecosystem.md
Adds ecosystem tab into documentation
To document related projects and SDKs
=> docs: add ecosystem documentation

cmd/follower.go, cmd/leader.go, cmd/maxprocs.go, cmd/maxprocs_linux.go, docs/changelog.md
The flag rest.address was handled in a different way on follower and a leader
=> bug: fix follower rest address handling

Makefile, cmd/leader.go, docs/changelog.md
=> bug: fix replication TLS

docs/changelog.md, storage/table/fsm/command_delete.go, storage/table/fsm/command_delete_test.go, storage/table/fsm/command_put.go, storage/table/fsm/command_put_test.go, storage/table/fsm/command_txn.go
Fix bugs in handling ErrNotFound pebble errors.
Add coverage in unit tests.
=> bug: put and delete prev and count errors

.github/workflows/lint.yml, Makefile
=> add: codeql action

Dockerfile, docs/Gemfile, docs/Gemfile.lock, docs/_config.yml, go.mod
=> deps: bump Go and just-the-docs version

Dockerfile, cmd/common.go, cmd/flags.go, cmd/follower.go, cmd/leader.go, docs/changelog.md, docs/operations_guide/cli/regatta_follower.md, docs/operations_guide/cli/regatta_leader.md, regattaserver/maintenance.go, replication/backup/backup.go, replication/backup/backup_test.go
Merge Maintenance with API port.
Simplifying the client development, simplifying the operations (one certificate and port less).
=> add: simplify server by removing maintenance API port

docs/changelog.md, regattaserver/encoding/proto/codec.go, regattaserver/encoding/zstd/grpc.go, regattaserver/encoding/zstd/grpc_test.go, regattaserver/grpc.go
* Support zstd compression
* To offer wider range of compression algorithms for specific use-cases.
UTs
=> add: zstd compression support + cleanup of proto errors

.github/labeler.yml
=> add: update labeler.yml

.golangci.yml, regattaserver/kv_test.go, regattaserver/replication_test.go, replication/snapshot/snapshot_test.go, storage/cluster/cluster_test.go, storage/cluster/dns/dns.go, storage/kv/kv_test.go, storage/logreader/cache.go, storage/logreader/cache_test.go, storage/queue_test.go, storage/table/fsm/command_delete.go, storage/table/fsm/command_delete_test.go, storage/table/fsm/command_put.go, storage/table/fsm/command_put_test.go, storage/table/fsm/command_test.go, storage/table/fsm/command_txn_test.go, storage/table/fsm/fsm_feature_test.go, storage/table/fsm/iter_test.go, storage/table/fsm/snapshot_test.go, storage/table/manager.go, storage/table/manager_test.go, util/rand_test.go
=> add: enable more linters, fix found issues

docs/Gemfile, docs/Gemfile.lock, docs/ecosystem.md, docs/proposals/000-rfc-template.md, docs/proposals/001-range-empty.md, docs/proposals/002-cursor-api.md, docs/proposals/003-replace-raft-lib.md, regattaserver/encoding/proto/codec.go, regattaserver/grpc.go
* Improving proposal docs with status
* Fixed a small issue with registering custom proto codec which allowed to not force its use through server opts.
=> docs: documentation improvements

regattaserver/replication.go, replication/worker.go, replication/worker_test.go, storage/limiter.go, storage/limiter_test.go
=> bug: fixes for replication changes in 0.5.x

.github/workflows/lint.yml, Dockerfile, docs/changelog.md, docs/contributing.md, go.mod, storage/table/fsm/snapshot_checkpoint.go
=> deps: bump to Go 1.22

replication/replication.go, replication/worker.go
The stats computation loop was unnecessarily tight leading to waste of CPU cycles at rest.
=> feat: improve repl worker CPU usage

raft/event.go, raft/internal/transport/metrics.go, storage/cluster/cluster.go, storage/table/manager.go
=> add: rename raft metrics, fix un-registration

docs/changelog.md, storage/engine_test.go, storage/table/fsm/fsm.go, storage/table/fsm/query.go, util/iter/iter.go
As per changelog description.
Added additional set of tests to cover this in the future.
=> bug: fix iterate range with specific key
